variables:
  IMAGE_NAME: gaV3
  IMAGE_TAG: ga_frontend

stages:
  - build

build:
  only:
    - alpha
  
  stage: build

  image: docker:latest

  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

  script:
    - DOCKER_BUILDKIT=1 docker buildx build --load -t $IMAGE_NAME:$IMAGE_TAG .
      docker stop ga_front || true &&
      docker rm ga_front || true &&
      docker run -dit --name ga_front -p 2000:3000/tcp $IMAGE_NAME:$IMAGE_TAG 

