variables:
  GCP_TAG: asia-south1-docker.pkg.dev/gamingarcade/gamingarcade/ga:frontend
  IMAGE_NAME: jainsiddharth1999/zeltatech
  IMAGE_TAG: ga_frontend

stages:
  - build
  - deploy
  - cleanup

build:
  only:
    - alpha
  tags:
    - alpha-ga
  stage: build

  image: docker:latest

  services:
    - docker:dind

  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

  script:
    - DOCKER_BUILDKIT=1 docker buildx build --load -t $IMAGE_NAME:$IMAGE_TAG .
    - docker tag $IMAGE_NAME:$IMAGE_TAG $GCP_TAG
    - docker buildx build --push -t $GCP_TAG .

deploy:
  only:
    - alpha
  tags:
    - alpha-ga
  stage: deploy

  before_script:
    - chmod 400 $SSH_KEY

  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@$ALPHA_SERVER_IP "
      gcloud auth configure-docker asia-south1-docker.pkg.dev &&
      docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
      docker stop ga_front || true &&
      docker rm ga_front || true &&
      docker rmi $GCP_TAG || true &&
      docker pull $GCP_TAG &&
      docker run -dit --name ga_front -p 2000:3000/tcp $GCP_TAG &&
      gcloud artifacts docker images delete --quiet "$GCP_TAG" || true "

cleanup:
  only:
    - alpha
  tags:
    - alpha-ga

  stage: cleanup

  image: docker:latest

  before_script:
    - chmod 400 $SSH_KEY

  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@$ALPHA_SERVER_IP
    - echo y | docker system prune
