variables:
  IMAGE_NAME: gav3
  IMAGE_TAG: ga_frontend

stages:
  - build

build:
  only:
    - alpha
  
  stage: build
  image: docker:latest

  script:
    - DOCKER_BUILDKIT=1 docker build -t $IMAGE_NAME:$IMAGE_TAG .    
    - docker stop $IMAGE_TAG || true &&
    - docker rm $IMAGE_TAG || true &&
    - docker run -dit --name $IMAGE_TAG -p 2000:3000/tcp $IMAGE_NAME:$IMAGE_TAG 


